# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-19 05:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='head_img',
        ),
    ]
