# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-21 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lostitem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='finditem',
            fields=[
                ('findid', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=10)),
                ('tele', models.CharField(max_length=20)),
                ('lostpla', models.CharField(max_length=20)),
                ('issuedate', models.DateTimeField(default=django.utils.timezone.now)),
                ('info', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-issuedate',),
            },
        ),
    ]
